### ISSUE TITLE
Discrepancies between bookmark and web method

### ISSUE THREAD

**Issue by davefuentes** [squizlabs/HTML_CodeSniffer#109]
I found some discrepancies using the bookmark and the online analizer you have at: http://squizlabs.github.io/HTML_CodeSniffer/

Also, when using pa11y, I see there are several differences in the results. Is this a known issue?

![HMTL Code Sniffer results using bookmark](http://i61.tinypic.com/2628dqw.png)
![HMTL Code Sniffer results using online tool](http://i60.tinypic.com/24pgui1.png)

**Comment by lwright-sq** [comment]
Hi,

Sorry for the very, very late reply on this one.

The difference between the bookmarklet and the front page tester could be due to other scripts having run since the source code was first generated, since the front page tester doesn't open a browser head-end - it just dumps things into a DOM rather than runs anything.

The pa11y tool (like our own command line contribution in Contrib/PhantomJS) uses a PhantomJS instance, which is a headless browser based on WebKit. HTMLCS can only work with the DOM it is provided, and it's possible that (a) PhantomJS isn't running all the scripts that inject elements into the DOM as on a real browser, and (b) some browsers (particularly IE, but also Firefox to a lesser extent) may create a slightly different DOM for their engine to process, which may affect the results very slightly.
