### ISSUE TITLE
Hidden Elements found by HTML_Code_Sniffer

### ISSUE THREAD

**Issue by reach2akram** [squizlabs/HTML_CodeSniffer#116]
I am testing an application in which HTML_Code sniffer identify some hidden elements also,
Below is an example : 

Below anchor element is hidden and not shown by code sniffer on UI by 'Point to Element' button , but still it captures that issue and shown.

Error : Anchor element found with no link content and no name and/or ID attribute.
Code Snippet :
<a class="sr-only" aria-hidden="true" href=""></a>

Here my question is that do we need to remove these hidden elements as well or it is fine and we can ignore it.

**Comment by lwright-sq** [comment]
Hi,

Your code snippet is not showing, can you please confirm?

I see

    <a href></a>

as in the source of your comment - is this what you're talking about?

If it's something like this... I'm actually not sure. What's happening is that HTMLCS will pass by elements that that have no content but are used as a "source anchor" (by including an ID or name attribute), as this is generally useful.

If it had a filled-in href attribute, it probably should be throwing an error because a link should normally contain link text that describes the link's purpose.

But if it has none of the above... I'm not sure what kind of limbo that leaves it in. Personally I'd remove them for code cleanliness purposes rather than anything else - or if it's meant to be used for something else (and actually contain content at some point), hiding it using CSS or something.

But I'd be leaning towards that it probably should be passed as "not inaccessible" because it actually doesn't -do- anything for anyone, and thus there are no accessibility issues with it - most of the things to do with accessibility have to do with making sure accessibility is equal, not necessarily "optimal".

**Comment by lwright-sq** [comment]
Closing (but not locking) due to no feedback in months.
