### ISSUE TITLE
html code sniffer local installation?

### ISSUE THREAD

**Issue by qaDream77** [squizlabs/HTML_CodeSniffer#132]
I have a shell script which runs pa11y on multiple sites and generates reports. I am looking to do this for internal sites (intranet), so they would be inaccessible to code sniffer. Is there a way to install code sniffer onto a machine or a server and have it run local sites? Any support would be greatly appreciated!

**Comment by lwright-sq** [comment]
Hi there,

Profuse apologies first off for the slow response!

I've never used pa11y myself but from what I can tell, but I don't think it's an issue. It doesn't use an online version of HTMLCS but uses a built one (stored in lib/vendor) and thus will have the same visibility as the rest of your pa11y install. You don't need a separate HTMLCS build, unless you wish to update the version inside pa11y from the version they have - I think they're roughly the same right now.

The main thing that will determine whether pa11y can get to it is if your intranet site has its own authentication (either HTTP or web-page based) - I'm not sure whether pa11y has the ability to send authentication details to it. This may inhibit its ability to get a view of your intranet site.

If the site is accessible without logging things in - even if it's IP restricted or only accessible on your internal network, if the server that runs pa11y (well, runs the Node.js instance that runs pa11y) has access to it, then it should be fine.

Since the name of this thread was made generic:
If you want to run a plain HTMLCS repo clone by itself on the command line, you can use [PhantomJS](https://www.phantomjs.org/) and a script provided in the Contrib/PhantomJS folder of the repo - PhantomJS provides a headless browser for this. (pa11y uses PhantomJS too.)
