### ISSUE TITLE
Offer a way to set the flavour of HTML to test with

### ISSUE THREAD

**Issue by luketw** [squizlabs/HTML_CodeSniffer#137]
As it stands, HTMLCS does not make any assumptions about the flavour of HTML one is running, because for the most part it does not matter - the DOM will still be what it is regardless of whether it is HTML, XHTML or whatever.

But there are instances where this matters, such as found at #133. Going between HTML 4.01 (including XHTML 1.0) and HTML5 (or WHATWG HTML), there have been some interpretation changes for certain tags. Most notably, presentation tags like "b", "i", and "small" are defined in a pseudo-semantic way in HTML5, and arguably shouldn't be throwing the same messages there as in HTML 4/XHTML 1. If HTMLCS eventually extends to raw HTML-level testing at some point, then whether it is defined as HTML or XHTML would make a difference in that too,.

Full documents should default to their DOCTYPE - this is available in a JavaScript property, except in earlier versions of IE (including IE8) which consider the DOCTYPE a comment (but may still be able to be parsed). But what's even more of a spanner in the works is, XHTML5 (ie. HTML 5's XML serialisation) recommends no DOCTYPE at all, making detection purely via doctype impossible. So there should still be some kind of override even for full documents, with a warning similar to what the W3C's HTML checker gives when overriding.

Document fragments would also need this override, although no extra messages would be required apart from a warning that document fragments cannot be conformant in and of themselves.

**Comment by wiseolddj** [comment]
:+1:

**Comment by andrewholgate** [comment]
:+1:  We've stumbled into this issue as well.

Any hints as to the architectural direction to take to achieve this within the project? It would be useful to hear from the maintainers before so that we can help provide a workable patch.

**Comment by lwright-sq** [comment]
Hi Andrew,

I'm still not particularly clued up on running node.js things via the command line, so I'm not sure how you would go about that part. Not yet sure about how you'd shoehorn it in as a standard option in the core of HTMLCS (to handle documents without a type, including XHTML5 docs) as I'd need to refresh my memory.

Usually the document type declaration is available using JavaScript's "document.doctype" property - however we didn't implement it initially because we wanted our results to be consistent as possible, and earlier versions (and document modes) of IE didn't actually parse DOCTYPEs as a document type rather than as a comment - essentially you needed IE9 and standards mode, and because IE8 compatibility was important, splitting handling of document type capabilities.

Now that IE8 isn't as important anymore - Microsoft is trying to push everyone to IE11 now, but documents under an Enterprise Mode policy would still resolve to IE8 Standards - it may be something that we could look at loosening, but then we'd need to decide what the default standard would be. As IE8 has no idea about HTML5, it's likely that HTML4.01 or XHTML1.0 would be appropriate as default. (Running off command line shouldn't have this problem as the underlying PhantomJS browser is a headless WebKit.)

So there would probably need to be a document type detection process early on (or otherwise is overruled by a switch) that tries to work out from document.doctype (if any) what version of HTML we might be working with, and then go from there - using the HTML version we determined prior to running of standards as opposed to using document.doctype directly in standards code.

Nothing firm in there I know, but just thinking of what might be the best way ahead, as although switching what standards do based on HTML dialect is fairly trivial, determining what that is is not a *completely* trivial thing in some cases.

**Comment by andrewholgate** [comment]
I see this issue as being broken down in 2 actionable parts:

# 1. Identification of DOCTYPE

## a) Auto detection of DOCTYPE

Ideally the identification of the DOCTYPE would be handled automatically but as described above it has several complications, twists and turns.

## b) Manual detection of DOCTYPE

As an MVP feature release, we could consider setting the DOCTYPE manual through a config flag such as `--doctype=html5` (as suggest by colleague @matthewmorek)

This would allow us to remove these false-positives and move onto 2.

# 2. Apply relevant standards to DOCTYPE

As the majority of standards apply to all of the DOCTYPES, I imagine this being managed as a blacklist of standards, those which do not need to be applied.

For example, for `html5` the following is not applicable:

```
[
  'WCAG2AA.Principle1.Guideline1_3.1_3_1.H73.3.NoSummary',
]
```

---

If you think this is a workable proposal for an MPV, I'd gladly put in some time to come up with a documented list of standards which are no applicable to specific DOCTYPES.

**Comment by ironikart** [comment]
This is probably not going to happen unless someone wants to submit a PR. Closing the issue.
