### ISSUE TITLE
headers are throwing an error with tfoot

### ISSUE THREAD

**Issue by 7mary4** [squizlabs/HTML_CodeSniffer#139]
I've got a package for testing automated testing libraries:
https://github.com/7mary4/a11y-control-test
The data-good.html file has a table with a tfoot. This is throwing an error because it expects all td cells to reference the th cells universally. 
In this case, the tfoot contains a th[scope="row"] and should only be referenced by the cell within its row. 
The current script is throwing an error because this row doesn't reference the column headers and the other rows are not referencing the tfoot's th.

**Comment by lwright-sq** [comment]
Hi Ted,

I'll have to take this one on notice, but your example doesn't seem "wrong" to me.

It's not really because of the tfoot, but because the table isn't the "clean", one row and one column of headers thing - it's getting confused because it's seeing the total TH stretch over three columns, and it would complain whether that was in tfoot or tbody. (The scope attribute is being ignored because HTMLCS considers headers attributes in preference to scope.)

It strengthens the idea of this being a warning and a manual check, because "you're always going to have exceptions to the rule"... but changing this would probably not be a trivial task because there are certain things that really *should* be errors and others that may need manual review (which in HTMLCS terminology should be a warning, not an error).

Things that probably should be errors, for instance, could include incomplete use of a technique (having headers attrs on some TDs and not others), or uses that don't make sense (eg. headers referencing IDs that are outside the table).

It's certainly food for thought though, so thanks for your report!

~ Luke

**Comment by 7mary4** [comment]
Thank you for the response. I too thought it was not specific to tfoot. 
I would agree this error message may be more of a warning than an error. 

The quality of codesniffer is so high that it made me double check my code and test with other services to make sure I wasn't missing something. So I would call that more of a victory than a defeat.
