### ISSUE TITLE
dependency version mismatch

### ISSUE THREAD

**Issue by bshack** [squizlabs/HTML_CodeSniffer#154]
getting this error on install, please review the dependency versions for this project

-----

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "shrinkwrap"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! invalid: have HTML_CodeSniffer@2.0.1 (expected: github:squizlabs/HTML_CodeSniffer#2.0.6) /Users/williamshackelford/Sites/shackstack/node_modules/access-sniff/node_modules/HTML_CodeSniffer
npm ERR! extraneous: HTML_CodeSniffer@2.0.1 /Users/williamshackelford/Sites/shackstack/node_modules/access-sniff/node_modules/HTML_CodeSniffer
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/williamshackelford/Sites/shackstack/npm-debug.log

**Comment by yargalot** [comment]
Just in note of this issue, @lwright-sq Can you please merge branch 2.0 into master, having releases going of the 2.0 branch and not from master is pretty confusing.

**Comment by lwright-sq** [comment]
@yargalot Noted, sorry about that - I was looking at giving it a proper reworking but have not have the chance to, so have folded 2.0 back into Master completely. Fair point that it probably should've been somewhere other than the Master branch - not sure what I was thinking there.

**Comment by yargalot** [comment]
Thanks!

**Comment by yargalot** [comment]
Oh also, quick question @lwright-sq , is there a 3.0 discussion going on somewhere?

**Comment by lwright-sq** [comment]
There's not and probably won't be for the foreseeable future, as it will depend on available resources.

The likely concept for a "next version" re-organisation was to reshape the tests into something generic - having tests described for "what they do" rather than "what Success Criteria they test", and then make better use of standards rulesets that way. For instance, instead of a "test for 1.4.3" and "test for 1.4.6", I was envisaging a generic "colour contrast" test and then having both the A/Double-A and Triple-A tests referring to that. (This is a similar process to how our sister project, [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) works.)

**Comment by yargalot** [comment]
Yeh that would make sense, Was looking through the code and thinking that. I guess Im asking because Im thinking of doing a major rewrite of it, but then again, since it'll be a pretty major design change Im wondering what the chances are of it being reintegrated into here.

Breifly thinking something like:
- Webpack build
- Switching modules over to a commonjs format
- ES6 (Babel)
- ESLint
- Travis.ci integration
- Jasmine testing (or something similar maybe )
- Maybe flow intergration for static typechecking etc 

From what you said above by making project based of function rather than tightly coupled to each rule the above wouldn't be too far from the mark.
