### ISSUE TITLE
insufficient contrast error incorrectly given for 14pt bold text

### ISSUE THREAD

**Issue by robfentress** [squizlabs/HTML_CodeSniffer#155]
The following code should pass, but throws a contrast error:
`<p>Sample: <span style="color: #7c7cff; background-color: #ffffff; font-size: 14pt; font-weight: bold;">I am 14pt bold text and should pass</span></p>`

The error is: 

> This element has insufficient contrast at this conformance level. Expected a contrast ratio of at least 4.5:1, but text in this element has a contrast ratio of 3.4:1. Recommendation: change text colour to #6666e9.

WCAG 2.0 AA requirement is 3:1 for large text, defined as 14 point and bold or larger, or 18 point or larger.  This text is 14pt bold, and so should pass.

**Comment by lwright-sq** [comment]
Hi Rob,

I'm going to accept this as a bug. It looks like my contrast calculations have an edge case that you've picked up.

They round down the calculated number of pixels returned by the computed style (based on the CSS pixel of 96 px/inch) before converting to points - and since 14pt is (18 2/3)px, it's calculating on 18px (=13.5pt) and not the full amount.
https://github.com/squizlabs/HTML_CodeSniffer/blob/master/Standards/WCAG2AAA/Sniffs/Principle1/Guideline1_4/1_4_3_Contrast.js#L69

Will get to it in the next release. Thanks for the report!
