### ISSUE TITLE
No error message appears when image (not for decoration) without alt text

### ISSUE THREAD

**Issue by liulijing** [squizlabs/HTML_CodeSniffer#179]
befor there was a error message if the image without alt text. However there is no more now. Not sure what happened to HTML_CodeSniffer

**Comment by ironikart** [comment]
Can you add a little more information, are you using the bookmarklet, or code directly from the repository? Can you provide some sample HTML code that you are testing on?

I can confirm the sniffs for empty alternative text for images still exist but that master branch has had some recent development that requires further testing for release. If you are using code on the master branch I am very interested to see how I can replicate this.

**Comment by liulijing** [comment]
Below is a example.
I tested it in CodeSniffer. Didn't get the error message for missing alt
text of the image.

<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>Untitled Document</title>
</head>

<body>
<p>This is a test for image alt text.</p>
<p> <img src="http://domaingang.com/wp-content/uploads/2012/02/example.png"
alt=""/></p>
</body>
</html>

Thanks for your help.
Lijing

**Comment by ironikart** [comment]
This is by design. The reason you didn't get an error message is you have an empty alt attribute which is a valid way of expressing a _decorative_ image. You've essentially told accessibility APIs that it's safe to ignore. The W3C website has a good [tutorial](https://www.w3.org/WAI/tutorials/images/decorative/) which explains this.
