### ISSUE TITLE
Mobile and desktop view 

### ISSUE THREAD

**Issue by mmdmeeran** [squizlabs/HTML_CodeSniffer#186]
Hey,

In screenshot ,its showing unrelated content which i could not able to identify in site.

This is link used: https://www.saiglobal.com/
![capture_standard_1 4 3](https://cloud.githubusercontent.com/assets/24872057/21585999/dfa0725e-d0f0-11e6-842d-f84e6dd02e39.PNG)

If you look into the screenshot, there wont be search or menu button.i am not sure how it got retrieved.

Do you have any configuration to switch for mobile and desktop view?

**Comment by ironikart** [comment]
I think the issue here is the context in which you ran HTML code sniffer over your code. The copy/paste function on the site doesn't account for different screen resolutions (I believe it uses an iframe) and the site you refer to caters for this using a responsive design technique with media queries. The example on the site you used is also more for demonstrative purposes rather than as a tool for properly validating your code, i.e. 'paste it here and see how it works'.

My suggestion would be to install the bookmarklet in your browser and run it with the browser window at the resolution you want to test, this way it should respect any content that would normally be hidden from assistive technologies.
