### ISSUE TITLE
 ReferenceError: HTMLCSAuditor is not defined

### ISSUE THREAD

**Issue by matejlednar** [squizlabs/HTML_CodeSniffer#192]
Hi

Latest update generates error on AMD projects - e.g. Dojo Toolkit, RequireJS.

source of error

 if (typeof define === 'function' && define.amd) {
        define(['htmlcs'], factory);
    }

**Comment by ironikart** [comment]
Do you have an example of the error you are receiving? It will be investigated but I'd like to make sure if a fix goes in it fixes your actual issue.

**Comment by matejlednar** [comment]
here is requireJS, but it is obfuscated and minified.
http://onlinewebsiteanalyzer.mldgroup.com/index.php

another internal project is using dojo toolkit and its AMD loader.

**Comment by clintoncrick** [comment]
We're seeing this issue as well. Chrome throws out this info (when ran as bookmarklet):
`VM363:1 Uncaught ReferenceError: HTMLCSAuditor is not defined
    at HTMLScriptElement.<anonymous> (<anonymous>:1:533)
    at HTMLScriptElement.sc.onload (<anonymous>:1:205)`

If we edit the lines @matejlednar highlighted to skip that check and then manually execute the code in our console, it works as expected.

**Comment by matejlednar** [comment]
I created snippet. Problem is your factory method. I created a fix.
    if (typeof define === 'function' && define.amd) {
        define(['htmlcs'], factory());
    } 

factory is a function, it must by an object. Please fix it.

**Comment by RobZoneNet** [comment]
I am getting the same thing. I am not sure how to fix.

**Comment by matejlednar** [comment]
use factory() instead of factory, see my comment above.

factory() returns object and this is correct argument., 
factory returns function what is incorrect argument.

**Comment by ironikart** [comment]
The issue here was related to the way the bookmarklet code was being built. If you used the bookmarklet on a web page that had libraries or core browser support for CommonJS or AMD style modules the wrapper was preferring to use that rather than to assign the exported code to the global namespace rendering the bookmarklet inoperable unless you ran the auditor code inside a module.

The resolution for this is an alteration to out build process for the bookmarklet (which is already a little bit customised). I've uploaded this new build so the next time you use the bookmarklet clear your browser cache and it should be fine to use on pages that use libraries like RequireJS or Dojo Toolkit.

I looked into the format for the AMD define() method and found it was working as expected for the latest versions of RequireJS (2.3.3) and Dojo Toolkit (1.12) when I tested non bookmarklet builds. The second argument for define in this case is the factory function which doesn't need to be immediately invoked returning it's object.

If anyone has further issues with the AMD format I'll push up my test cases somewhere.

**Comment by clintoncrick** [comment]
This has solved the issue for me. Thank you.

**Comment by RobZoneNet** [comment]
Thank you, this also was fixed the issue for me.

**Comment by joeyciechanowicz** [comment]
This seems to have come back with `2.4.0`. In `build/HTMLCS.js` is has:

```
if (typeof define === 'function' && define.amd) {
     define('[htmlcs'], factory);
}
```

**Comment by ironikart** [comment]
@joeyciechanowicz The fix I did for this issues was specifically targeted at the bookmarklet build. I published your recent pull request to a new version 2.4.1 on npm, I'm hoping the 2 are related. If not, I don't have a good test case set up for using amd with HTMLCS and a solid example of how it's being used would really help debugging it. I couldn't see any evidence of uglification mangling the amd wrapper.
