### ISSUE TITLE
HTML code sniffer sniffs against first argument standard 

### ISSUE THREAD

**Issue by rakeshkmr516** [squizlabs/HTML_CodeSniffer#217]
HI @ironikart 
I have executed the below code to sniff with multiple standards however it executes against the first argument of Level A. Could you please let me know any changes I need to make to run against multiple standards 
String jquery_content = Jsoup.connect("http://squizlabs.github.io/HTML_CodeSniffer/build/HTMLCS.js").ignoreContentType(true).execute().body();
		js.executeScript(jquery_content);
	
		js.executeScript("window.HTMLCS_RUNNER.run('WCAG2A','WCAG2AAA');");

Note:- Although AAA consists level A standards would like to run and report them

Ran 3times and appended the json however is there anyway to run standards separated by commas

**Comment by ironikart** [comment]
By design, that script only runs against one standard at a time because of the reason you mentioned ("AAA consists level A standards"). If you want to report on all 3 I'm afraid you'll have to either run it 3 seperate times or write a custom filter for the AAA level of conformance that can separate failures into A and AA.

**Comment by rakeshkmr516** [comment]
Thank you @ironikart . Ran the sniffer 3 times with different standards and appended the result to json file to make people happy to analyze violations at single place
