### ISSUE TITLE
Keep Github page Auditor version in sync with build version

### ISSUE THREAD

**Issue by andrewholgate** [squizlabs/HTML_CodeSniffer#293]
The [HTML_CodeSniffer Github page](http://squizlabs.github.io/HTML_CodeSniffer/) says the Auditor version available is: `2.1.1`

However when I check [the version that would be added to the bookmark](http://squizlabs.github.io/HTML_CodeSniffer/build/HTMLCS.js) it turns out it's using the latest build version:

```
/*! html_codesniffer - v2.5.1 - 2020-04-14 */
```

It would be a good idea to keep the Github info up-to-date with the build version.

**Comment by gsherwood** [comment]
Thanks for bringing this to our attention. I've actually removed the version number there because it's not being kept up to date and we don't published the changelog on the public site any more. The Github releases page is the best place to get info, although I noticed that we forgot to publish the draft notes for the last couple of versions, so I've fixed that too.
